Repository framgia/sph-flutter, pull requests merged in 2023-07, with the labels that each got.

#27 [SIM_FLUTTER-78] [Integrate] Display users dynamically
  backend/app/Http/Controllers/UserController.php
  backend/app/Models/User.php
  frontend/lib/src/controllers/admin_user_list_controller.dart
  frontend/lib/src/controllers/home_screen_controller.dart
  frontend/lib/src/features/account_details/account_details_page.dart
  frontend/lib/src/features/admin_user_list/admin_user_list_page.dart
  frontend/lib/src/features/admin_user_list/components/user_list_tile.dart
  frontend/lib/src/features/home_screen.dart
  frontend/lib/src/features/login/login_page.dart
  frontend/lib/src/features/transaction_history/transaction_history.dart
  frontend/lib/src/helper/dio.dart
  frontend/lib/src/models/user.dart
  frontend/lib/src/navigators/users_list_screen_navigator.dart
  frontend/lib/src/services/user_service.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer : Redempto, Code Reviewer: Rob

#30 [SIM_FLUTTER-94] [Integrate] User should stay logged in once user goes back to the application
  backend/app/Http/Middleware/LogRequest.php
  frontend/lib/src/controllers/login_controller.dart
  frontend/lib/src/features/login/login_page.dart
  frontend/lib/src/helper/dio.dart
  frontend/lib/src/services/user_service.dart
Labels: QA Reviewer : Derick, Approved by QA, Code Reviewer : Redempto

#39 [SIM_FLUTTER-13] [INTEGRATE] Display searched user
  backend/app/Http/Controllers/UserController.php
  backend/app/Models/User.php
  backend/routes/api.php
  frontend/lib/src/components/input/search_field.dart
  frontend/lib/src/controllers/admin_user_list_controller.dart
  frontend/lib/src/features/admin_user_list/admin_user_list_page.dart
  frontend/lib/src/services/user_service.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#42 [SIM_FLUTTER-46] [INTEGRATE] Create and implement admin delete user
  frontend/lib/src/controllers/admin_user_list_controller.dart
  frontend/lib/src/features/admin_user_list/admin_user_list_page.dart
  frontend/lib/src/features/admin_user_list/components/user_delete_dialog.dart
  frontend/lib/src/features/admin_user_list/components/user_list_tile.dart
  frontend/lib/src/services/user_service.dart
Labels: QA Reviewer : Derick, Approved by QA, Code Reviewer: Stephen

#36 [SIM_FLUTTER-95] [Integrate] Dynamically change navbar
  frontend/lib/src/controllers/home_screen_controller.dart
  frontend/lib/src/features/home_screen.dart
  frontend/lib/src/features/login/login_page.dart
  frontend/lib/src/models/user.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Rob

#38 [SIM_FLUTTER-6] [Integrate] Implement user forget password in the FE
  backend/app/Exceptions/TransactionException.php
  backend/app/Http/Controllers/AuthController.php
  backend/app/Http/Middleware/LogRequest.php
  backend/app/Http/Requests/Auth/ForgotPasswordRequest.php
  backend/app/Http/Requests/Auth/ResetPasswordRequest.php
  frontend/lib/src/controllers/forgot_password_controller.dart
  frontend/lib/src/controllers/reset_password_controller.dart
  frontend/lib/src/features/login/login_page.dart
  frontend/lib/src/features/password_reset/components/reset_password_page.dart
  frontend/lib/src/features/password_reset/forgot_password_page.dart
  frontend/lib/src/features/password_reset/password_reset_page.dart
  frontend/lib/src/features/user_profile/profile_change_password.dart
  frontend/lib/src/helper/dialog/show_alert_dialog.dart
  frontend/lib/src/helper/dio.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#34 [SIM_FLUTTER-39] [Integrate] Implement user can sign-up
  frontend/lib/src/controllers/sign_up_controller.dart
  frontend/lib/src/features/sign_up/components/breadcrumb.dart
  frontend/lib/src/features/sign_up/sign_up_flow.dart
  frontend/lib/src/features/sign_up/sign_up_step_one.dart
  frontend/lib/src/features/sign_up/sign_up_step_two.dart
Labels: QA Reviewer : Derick, Approved by QA, Code Reviewer : Redempto

#44 [SIM_FLUTTER-61] [Integrate] Implement accounts API in dashboard
  .vscode/launch.json
  backend/app/Http/Controllers/AuthController.php
  backend/app/Models/User.php
  frontend/lib/src/components/auth/auth_header.dart
  frontend/lib/src/controllers/auth_header_controller.dart
  frontend/lib/src/controllers/dashboard_controller.dart
  frontend/lib/src/features/dashboard/components/account_card.dart
  frontend/lib/src/features/dashboard/dashboard.dart
  frontend/lib/src/features/login/login_page.dart
  frontend/lib/src/helper/dio.dart
  frontend/lib/src/helper/storage.dart
  frontend/lib/src/models/account.dart
  frontend/lib/src/services/account_service.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer : Redempto

#37 [SIM_FLUTTER-18][Integrate] Display User updated profile details dynamically
  frontend/lib/src/components/input/input_field.dart
  frontend/lib/src/controllers/user_profile_controller.dart
  frontend/lib/src/features/home_screen.dart
  frontend/lib/src/features/user_profile/profile_info.dart
  frontend/lib/src/models/user.dart
  frontend/lib/src/services/user_service.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer : Redempto

#45 [SIM_FLUTTER-101] [BE] Add account_name column to the Account table.
  backend/app/Http/Controllers/AuthController.php
  backend/database/migrations/2023_07_04_095529_add_account_name_to_account_table.php
  frontend/lib/src/features/dashboard/components/account_card.dart
  frontend/lib/src/models/account.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Rob

#50 [SIM_FLUTTER-74] [Integrate] Implement user can withdraw cash
  frontend/lib/src/components/transaction_component/transaction_component.dart
  frontend/lib/src/controllers/transaction_controller.dart
  frontend/lib/src/features/account_details/account_details_page.dart
  frontend/lib/src/features/dashboard/components/account_card.dart
  frontend/lib/src/features/dashboard/dashboard.dart
  frontend/lib/src/features/transaction_history/components/transaction_card.dart
  frontend/lib/src/features/transaction_history/data/data.dart
  frontend/lib/src/helper/dio.dart
  frontend/lib/src/models/account.dart
  frontend/lib/src/models/transaction.dart
  frontend/lib/src/services/transaction_service.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Rob

#47 [SIM_FLUTTER-103] [Bug] Update name in dropdown after updating profile
  frontend/lib/src/components/auth/auth_header.dart
  frontend/lib/src/controllers/auth_header_controller.dart
  frontend/lib/src/controllers/user_profile_controller.dart
  frontend/lib/src/features/login/login_page.dart
  frontend/lib/src/features/user_profile/profile_info.dart
  frontend/lib/src/helper/user_full_name.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Egie

#54 [SIM_FLUTTER-111] [Improvement] Add new account number column in Account Table
  backend/app/Http/Requests/ProfileRequest.php
  backend/app/Models/Account.php
  backend/app/Providers/AppServiceProvider.php
  backend/app/Providers/EventServiceProvider.php
  backend/app/Traits/UniqueCodeTrait.php
  backend/app/Traits/Uuid.php
  backend/composer.json
  backend/database/migrations/2023_07_07_023101_add_account_number_to_accounts_table.php
  backend/database/seeders/fixes/AccountFixSeeder.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#48 [SIM_FLUTTER-99] [FE] Create add account modal
  frontend/lib/src/components/input/dropdown.dart
  frontend/lib/src/controllers/add_account_controller.dart
  frontend/lib/src/features/dashboard/components/add_account_dialog.dart
  frontend/lib/src/features/home_screen.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#49 [SIM_FLUTTER-24] [Integrate] Display user account details dynamically
  frontend/lib/src/controllers/account_details_controller.dart
  frontend/lib/src/controllers/home_screen_controller.dart
  frontend/lib/src/features/account_details/account_details_page.dart
  frontend/lib/src/features/home_screen.dart
  frontend/lib/src/helper/dio.dart
  frontend/lib/src/navigators/dashboard_screen_navigator.dart
  frontend/lib/src/services/account_service.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Rob

#57 [SIM_FLUTTER-114] [Bug] Add accountName in account_details_controller.dart
  frontend/lib/src/controllers/account_details_controller.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#53 [SIM_FLUTTER-100] [BE] Create add new account API
  backend/app/Http/Controllers/AccountController.php
  backend/app/Http/Requests/AccountPostRequest.php
  backend/app/Models/Account.php
  backend/app/Models/Transaction.php
  backend/app/Models/User.php
  backend/config/enums.php
  backend/database/factories/AccountFactory.php
  backend/database/migrations/2023_07_07_091358_change_account_type_column_in_account_table.php
  backend/database/seeders/AccountSeeder.php
  backend/routes/api.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Rob

#58 [SIM_FLUTTER-34] [Integrate] Implement user can deposit cash
  frontend/lib/src/components/input/input_field.dart
  frontend/lib/src/components/transaction_component/transaction_component.dart
  frontend/lib/src/controllers/account_details_controller.dart
  frontend/lib/src/models/account.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#56 [SIM_FLUTTER-53] [Integrate] Display the lists of transactions
  backend/app/Http/Controllers/TransactionController.php
  backend/app/Http/Resources/TransactionResource.php
  backend/app/Models/Transaction.php
  backend/database/seeders/TransactionSeeder.php
  frontend/lib/src/components/transaction_component/transaction_component.dart
  frontend/lib/src/controllers/transaction_controller.dart
  frontend/lib/src/features/account_details/account_details_page.dart
  frontend/lib/src/features/dashboard/components/account_card.dart
  frontend/lib/src/features/transaction_history/components/transaction_card.dart
  frontend/lib/src/features/transaction_history/data/data.dart
  frontend/lib/src/features/transaction_history/transaction_history.dart
  frontend/lib/src/models/transaction.dart
  frontend/lib/src/navigators/dashboard_screen_navigator.dart
  frontend/lib/src/services/transaction_service.dart
Labels: QA Reviewer : Derick, Approved by QA, Code Reviewer: Stephen

#61 [SIM_FLUTTER-115] [Bug] User Accounts are not displayed
  frontend/lib/src/controllers/account_details_controller.dart
  frontend/lib/src/enums/account_enum.dart
  frontend/lib/src/models/account.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Rob

#60 [SIM_FLUTTER-113] [Bug] Login page rebuilds again and again
  frontend/lib/src/controllers/login_controller.dart
  frontend/lib/src/features/login/login_page.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Rob

#52 [SIM_FLUTTER-49] [Integrate] Implement user transfer money to other user
  backend/app/Http/Controllers/TransactionController.php
  backend/app/Http/Requests/TransactionPostRequest.php
  backend/app/Models/Account.php
  frontend/lib/src/components/transaction_component/transaction_component.dart
  frontend/lib/src/controllers/account_details_controller.dart
  frontend/lib/src/controllers/dashboard_controller.dart
  frontend/lib/src/controllers/transaction_controller.dart
  frontend/lib/src/features/account_details/account_details_page.dart
  frontend/lib/src/features/dashboard/components/account_card.dart
  frontend/lib/src/features/transaction_history/components/transaction_card.dart
  frontend/lib/src/models/account.dart
  frontend/lib/src/models/transaction.dart
  frontend/lib/src/services/account_service.dart
  frontend/lib/src/services/transaction_service.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#55 [SIM_FLUTTER-106] [FE] Update UI in withdrawal
  frontend/lib/src/components/input/dropdown.dart
  frontend/lib/src/components/transaction_component/transaction_component.dart
  frontend/lib/src/controllers/transaction_controller.dart
  frontend/lib/src/enums/transaction_enum.dart
  frontend/lib/src/features/account_details/account_details_page.dart
  frontend/lib/src/features/dashboard/components/account_card.dart
  frontend/lib/src/features/transaction_history/transaction_history.dart
  frontend/lib/src/helper/capitalize_first_letter.dart
  frontend/lib/src/models/transaction.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#63 [SIM_FLUTTER-116][Bug] An "Uncaught error" will appear if the user leaves the middle name blank and clicks on "Save."
  backend/app/Http/Controllers/UserController.php
  frontend/lib/src/controllers/user_profile_controller.dart
  frontend/lib/src/features/user_profile/profile_info.dart
  frontend/lib/src/helper/user_full_name.dart
  frontend/lib/src/services/user_service.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#62 [SIM_FLUTTER-102] [INTEGRATE] User can add new account type
  backend/config/enums.php
  backend/database/migrations/2023_07_13_055921_update_account_types_in_accounts_table.php
  backend/database/seeders/AccountSeeder.php
  frontend/lib/src/controllers/add_account_controller.dart
  frontend/lib/src/enums/account_enum.dart
  frontend/lib/src/features/account_details/account_details_page.dart
  frontend/lib/src/features/dashboard/components/account_card.dart
  frontend/lib/src/features/dashboard/components/add_account_dialog.dart
  frontend/lib/src/helper/dio.dart
  frontend/lib/src/models/account.dart
  frontend/lib/src/services/account_service.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#67 [Team] Thunder client
  README.md
  thunder-tests/collections/tc_col_accounts.json
  thunder-tests/collections/tc_col_auth.json
  thunder-tests/collections/tc_col_others.json
  thunder-tests/collections/tc_col_transactions.json
  thunder-tests/collections/tc_col_users.json
  thunder-tests/environments/tc_env_derick.json
  thunder-tests/environments/tc_env_global.json
  thunder-tests/environments/tc_env_stephen.json
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev

#68 [SIM_FLUTTER-117][Improvement] Change Recipient's Name to Recipient's Complete Name
  frontend/lib/src/components/transaction_component/transaction_component.dart
  frontend/lib/src/controllers/account_details_controller.dart
  frontend/lib/src/features/dashboard/components/account_card.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#65 [SIM_FLUTTER-69] [BE] Create spending breakdown API
  backend/app/Http/Controllers/AccountController.php
  backend/app/Http/Controllers/TransactionController.php
  backend/app/Http/Requests/SpendingBreakdownRequest.php
  backend/app/Http/Resources/SpendingBreakdownResource.php
  backend/app/Models/Account.php
  backend/routes/api.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Rob

#69 [SIM_FLUTTER-112] [Improvement] Add "Account Number" in Dashboard and Account Details page
  frontend/lib/src/features/account_details/account_details_page.dart
  frontend/lib/src/features/dashboard/components/account_card.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Rob

#71 [SIM_FLUTTER-96] [Bug] The name will duplicate when the user scrolls down and then clicks on it.
  frontend/lib/src/components/auth/auth_header.dart
  frontend/lib/src/components/auth/components/logout_dropdown.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#64 [SIM_FLUTER-59] [INTEGRATE] Implement filter account transaction by date
  frontend/lib/src/components/input/date_picker_field.dart
  frontend/lib/src/controllers/transaction_controller.dart
  frontend/lib/src/features/transaction_history/transaction_history.dart
  frontend/lib/src/navigators/dashboard_screen_navigator.dart
  frontend/lib/src/services/transaction_service.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Rob

#70 [SIM_FLUTTER-107] [INTEGRATE] Implement Category In Withdrawal
  frontend/lib/src/components/transaction_component/transaction_component.dart
  frontend/lib/src/features/account_details/account_details_page.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#72 [SIM_FLUTTER-118] [Bug] Update name in dropdown after updating profile
  frontend/lib/src/components/auth/auth_header.dart
  frontend/lib/src/components/auth/components/logout_dropdown.dart
  frontend/lib/src/helper/truncate.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#73 [SIM_FLUTTER-81] [Integrate] Implement Admin Update User
  backend/app/Http/Requests/UpdatePasswordRequest.php
  backend/app/Rules/MatchOldPassword.php
  frontend/lib/src/controllers/user_profile_controller.dart
  frontend/lib/src/features/admin_user_list/components/user_list_tile.dart
  frontend/lib/src/features/home_screen.dart
  frontend/lib/src/features/user_profile/profile_change_password.dart
  frontend/lib/src/features/user_profile/profile_info.dart
  frontend/lib/src/navigators/users_list_screen_navigator.dart
  frontend/lib/src/services/user_service.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#75 [SIM_FLUTTER-119][Bug] Display the Middle Initial in the User List
  frontend/lib/src/features/admin_user_list/components/user_list_tile.dart
  frontend/lib/src/helper/user_full_name.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#66 [SIM_FLUTTER-56] [Integrate] Implement user filter by category/type of transaction
  frontend/lib/src/controllers/transaction_controller.dart
  frontend/lib/src/enums/transaction_enum.dart
  frontend/lib/src/features/account_details/account_details_page.dart
  frontend/lib/src/features/transaction_history/transaction_history.dart
  frontend/lib/src/services/transaction_service.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#77 [SIM_FLUTTER-122] [REFACTOR] Convert TransactionEnum to Enhanced Enum
  frontend/lib/src/components/transaction_component/transaction_component.dart
  frontend/lib/src/controllers/transaction_controller.dart
  frontend/lib/src/enums/transaction_enum.dart
  frontend/lib/src/features/account_details/account_details_page.dart
  frontend/lib/src/features/dashboard/components/account_card.dart
  frontend/lib/src/features/transaction_history/transaction_history.dart
  frontend/lib/src/models/transaction.dart
  frontend/lib/src/services/transaction_service.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#74 [SIM_FLUTTER-68] [FE] Create spending breakdown page
  frontend/assets/svg/bills.svg
  frontend/assets/svg/food.svg
  frontend/assets/svg/miscellaneous.svg
  frontend/assets/svg/savings.svg
  frontend/assets/svg/transportation.svg
  frontend/lib/src/components/graph.dart
  frontend/lib/src/components/indicator.dart
  frontend/lib/src/components/input/dropdown.dart
  frontend/lib/src/components/spending_breakdown_card.dart
  frontend/lib/src/const/spending_breakdown_filter.dart
  frontend/lib/src/const/spending_breakdown_test_data.dart
  frontend/lib/src/controllers/graph_controller.dart
  frontend/lib/src/controllers/spending_breakdown_controller.dart
  frontend/lib/src/features/account_details/account_details_page.dart
  frontend/lib/src/features/spending_breakdown/spending_breakdown_page.dart
  frontend/lib/src/helper/get_spending_category_icon.dart
  frontend/lib/src/helper/transaction_category_color.dart
  frontend/lib/src/models/spending_breakdown.dart
  frontend/lib/src/navigators/dashboard_screen_navigator.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#76 [SIM_FLUTTER-123] [BUG] [BE] TransactionController index not working on /transactions route
  backend/app/Http/Controllers/TransactionController.php
  backend/app/Providers/AppServiceProvider.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Rob

#79 [SIM_FLUTTER-128] [BUG] [FE] Rename Transaction Categories
  frontend/lib/src/components/graph.dart
  frontend/lib/src/const/spending_breakdown_test_data.dart
  frontend/lib/src/helper/get_spending_category_icon.dart
  frontend/lib/src/helper/transaction_category_color.dart
  frontend/lib/src/models/spending_breakdown.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen, high prio

#80 [SIM_FLUTTER-125] [IMPROVEMENT] Update account model to use static constructor
  frontend/lib/src/enums/account_enum.dart
  frontend/lib/src/enums/transaction_enum.dart
  frontend/lib/src/models/account.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#81 [SIM_FLUTTER-126] [REFACTOR] Resolve TODO: Get the auth token form BE
  frontend/lib/src/components/auth/auth_header.dart
  frontend/lib/src/components/spending_breakdown_card.dart
  frontend/lib/src/controllers/auth_header_controller.dart
  frontend/lib/src/navigators/dashboard_screen_navigator.dart
  frontend/lib/src/navigators/profile_screen_navigator.dart
  frontend/lib/src/navigators/users_list_screen_navigator.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#78 [SIM_FLUTTER-120] [Bug] The newly created account type will not displayed automatically if lists of accounts are empty
  frontend/lib/src/features/dashboard/dashboard.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#82 [SIM_FLUTTER-121] [REFACTOR] Change classname of ScreenArguments for Account pages
  frontend/lib/src/features/account_details/account_details_page.dart
  frontend/lib/src/features/dashboard/components/account_card.dart
  frontend/lib/src/features/spending_breakdown/spending_breakdown_page.dart
  frontend/lib/src/features/transaction_history/transaction_history.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#84 [SIM_FLUTTER-130] [Improvement] Display by DESC order
  backend/app/Http/Controllers/TransactionController.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#85 [SIM_FLUTTER-132] [Improvement] Display List of Accounts by DESC order
  backend/app/Http/Controllers/AccountController.php
  thunder-tests/collections/tc_col_accounts.json
  thunder-tests/collections/tc_col_auth.json
  thunder-tests/environments/tc_env_escabillas.json
  thunder-tests/environments/tc_env_stephen.json
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#87 [SIM_FLUTTER-129] [BUG] Spam-clicking confirm button on transaction pop-ups registers multiple transactions
  frontend/lib/src/components/transaction_component/transaction_component.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#83 [SIM_FLUTTER-70] [Integrate] Implement display spending breakdown dynamically
  frontend/lib/src/components/empty_graph.dart
  frontend/lib/src/components/graph.dart
  frontend/lib/src/components/legend_section.dart
  frontend/lib/src/components/transaction_component/transaction_component.dart
  frontend/lib/src/const/spending_breakdown_test_data.dart
  frontend/lib/src/controllers/spending_breakdown_controller.dart
  frontend/lib/src/features/account_details/account_details_page.dart
  frontend/lib/src/features/spending_breakdown/spending_breakdown_page.dart
  frontend/lib/src/helper/dio.dart
  frontend/lib/src/models/spending_breakdown.dart
  frontend/lib/src/services/account_service.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen
