Repository framgia/sph-flutter, pull requests merged in 2023-06, with the labels that each got.

#2 [BE] Create Docker Setup for Database
  backend/.gitignore
  backend/docker-compose.yml
Labels: QA Reviewer : Derick, Code Reviewer : Karlo, Approved by QA, Approved by Dev

#1 [SIM_FLUTTER-35] [FE] Create user forgot password page
  frontend/analysis_options.yaml
  frontend/assets/fonts/Nunito/Nunito-Italic-VariableFont_wght.ttf
  frontend/assets/fonts/Nunito/Nunito-VariableFont_wght.ttf
  frontend/assets/fonts/Nunito/OFL.txt
  frontend/assets/fonts/Nunito/README.txt
  frontend/assets/fonts/Nunito/static/Nunito-Black.ttf
  frontend/assets/fonts/Nunito/static/Nunito-BlackItalic.ttf
  frontend/assets/fonts/Nunito/static/Nunito-Bold.ttf
  frontend/assets/fonts/Nunito/static/Nunito-BoldItalic.ttf
  frontend/assets/fonts/Nunito/static/Nunito-ExtraBold.ttf
  frontend/assets/fonts/Nunito/static/Nunito-ExtraBoldItalic.ttf
  frontend/assets/fonts/Nunito/static/Nunito-ExtraLight.ttf
  frontend/assets/fonts/Nunito/static/Nunito-ExtraLightItalic.ttf
  frontend/assets/fonts/Nunito/static/Nunito-Italic.ttf
  frontend/assets/fonts/Nunito/static/Nunito-Light.ttf
  frontend/assets/fonts/Nunito/static/Nunito-LightItalic.ttf
  frontend/assets/fonts/Nunito/static/Nunito-Medium.ttf
  frontend/assets/fonts/Nunito/static/Nunito-MediumItalic.ttf
  frontend/assets/fonts/Nunito/static/Nunito-Regular.ttf
  frontend/assets/fonts/Nunito/static/Nunito-SemiBold.ttf
  frontend/assets/fonts/Nunito/static/Nunito-SemiBoldItalic.ttf
  frontend/assets/images/corner.png
  frontend/lib/main.dart
  frontend/lib/src/components/auth/auth_header.dart
  frontend/lib/src/components/input/input_field.dart
  frontend/lib/src/features/password_reset/password_reset_page.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: QA Reviewer : Derick, Code Reviewer : Karlo, Approved by QA, Approved by Dev, Code Reviewer : Redempto

#4 [BE] Create DB migrations
  backend/app/Http/Controllers/AccountController.php
  backend/app/Http/Controllers/TransactionController.php
  backend/app/Models/Account.php
  backend/app/Models/Transaction.php
  backend/app/Models/User.php
  backend/database/migrations/2014_10_12_000000_create_users_table.php
  backend/database/migrations/2023_06_09_025916_create_accounts_table.php
  backend/database/migrations/2023_06_09_025950_create_transactions_table.php
Labels: QA Reviewer : Derick, Code Reviewer : Karlo, Approved by QA, Approved by Dev

#15 [SIM_FLUTTER-19][FE] Create user dashboard page
  frontend/assets/images/sph-flutter-logo.png
  frontend/assets/svg/home.svg
  frontend/assets/svg/profile_settings.svg
  frontend/lib/main.dart
  frontend/lib/src/components/templates/header_image.dart
  frontend/lib/src/features/dashboard/components/account_card.dart
  frontend/lib/src/features/dashboard/components/account_card_button.dart
  frontend/lib/src/features/dashboard/dashboard.dart
  frontend/lib/src/features/home_screen.dart
  frontend/lib/src/models/account.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen, high prio

#7 [SIM_FLUTTER-40] [FE] Create search bar
  frontend/analysis_options.yaml
  frontend/lib/main.dart
  frontend/lib/src/components/input/search_field.dart
  frontend/lib/src/controllers/home_screen_controller.dart
  frontend/lib/src/features/home_screen.dart
  frontend/lib/src/features/indiviual_components/search_field_page.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer : Redempto

#5 [SIM_FLUTTER-82] [BE] Apply linters to the repository
  .pre-commit-config.yaml
  .vscode/tasks.json
  backend/.gitignore
  backend/app/Console/Kernel.php
  backend/app/Http/Middleware/RedirectIfAuthenticated.php
  backend/app/Models/User.php
  backend/app/Providers/AppServiceProvider.php
  backend/app/Providers/AuthServiceProvider.php
  backend/composer.json
  backend/server.php
  backend/tests/Feature/ExampleTest.php
Labels: QA Reviewer : Derick, Code Reviewer : Karlo, Approved by QA, Approved by Dev

#3 [SIM_FLUTTER-10] [FE] Create User Login Page
  .vscode/launch.json
  frontend/lib/main.dart
  frontend/lib/src/components/auth/auth_header.dart
  frontend/lib/src/components/button/button.dart
  frontend/lib/src/components/input/input_field.dart
  frontend/lib/src/components/templates/header_image.dart
  frontend/lib/src/features/dashboard/dashboard.dart
  frontend/lib/src/features/home_screen.dart
  frontend/lib/src/features/login/login_page.dart
  frontend/lib/src/features/password_reset/password_reset_page.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer : Redempto

#6 [SIM_FLUTTER-27] [FE] Create user profile page
  frontend/assets/svg/list.svg
  frontend/lib/main.dart
  frontend/lib/src/components/auth/auth_header.dart
  frontend/lib/src/components/breadcrumb.dart
  frontend/lib/src/components/button.dart
  frontend/lib/src/components/button/button.dart
  frontend/lib/src/components/input/date_picker_field.dart
  frontend/lib/src/components/input/input_field.dart
  frontend/lib/src/components/label.dart
  frontend/lib/src/controllers/home_screen_controller.dart
  frontend/lib/src/features/dashboard/dashboard.dart
  frontend/lib/src/features/home_screen.dart
  frontend/lib/src/features/indiviual_components/search_field_page.dart
  frontend/lib/src/features/login/login_page.dart
  frontend/lib/src/features/password_reset/password_reset_page.dart
  frontend/lib/src/features/user_profile/profile_change_password.dart
  frontend/lib/src/features/user_profile/profile_info.dart
  frontend/lib/src/navigators/custom_page_route.dart
  frontend/lib/src/navigators/dashboard_screen_navigator.dart
  frontend/lib/src/navigators/profile_screen_navigator.dart
  frontend/lib/src/navigators/settings_screen_navigator.dart
Labels: QA Reviewer : Derick, Approved by QA, Code Reviewer: Stephen

#9 [SIM_FLUTTER-42] [BE] Create get user list API
  README.md
  backend/app/Http/Controllers/AccountController.php
  backend/app/Http/Controllers/TransactionController.php
  backend/app/Http/Controllers/UserController.php
  backend/app/Http/Resources/UserResource.php
  backend/app/Models/Account.php
  backend/app/Models/Transaction.php
  backend/app/Models/User.php
  backend/composer.lock
  backend/database/factories/UserFactory.php
  backend/database/migrations/2023_06_09_025950_create_transactions_table.php
  backend/database/seeders/UserSeeder.php
  backend/routes/api.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Rob

#10 [SIM_FLUTTER-31] [BE] Create User Login API
  backend/app/Exceptions/Handler.php
  backend/app/Http/Controllers/UserController.php
  backend/app/Http/Resources/LoginResource.php
  backend/app/Models/User.php
  backend/database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
  backend/routes/api.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Rob

#8 [SIM_FLUTTER-15] [FE] Create Admin User List Page
  .vscode/launch.json
  frontend/.gitignore
  frontend/assets/svg/trash.svg
  frontend/lib/main.dart
  frontend/lib/src/components/input/search_field.dart
  frontend/lib/src/features/admin_user_list/admin_user_list_page.dart
  frontend/lib/src/features/admin_user_list/components/user_delete_dialog.dart
  frontend/lib/src/features/admin_user_list/components/user_list_tile.dart
  frontend/lib/src/navigators/settings_screen_navigator.dart
Labels: QA Reviewer : Derick, Approved by QA, Code Reviewer: Stephen

#12 SIM_FLUTTER-29 [FE] Create deposit cash, transfer money, withdraw cash component
  frontend/lib/src/components/transaction_component/transaction_component.dart
  frontend/lib/src/features/dashboard/components/account_card.dart
  frontend/lib/src/features/dashboard/components/account_card_button.dart
  frontend/lib/src/helper/dialog/show_alert_dialog.dart
Labels: QA Reviewer : Derick, Approved by QA, Code Reviewer: Stephen, Code Reviewer: Rob

#16 [SIM_FLUTTER-51] [FE] Create transaction history page
  frontend/lib/main.dart
  frontend/lib/src/components/input/date_picker_field.dart
  frontend/lib/src/components/input/dropdown.dart
  frontend/lib/src/controllers/home_screen_controller.dart
  frontend/lib/src/controllers/transaction_controller.dart
  frontend/lib/src/features/dashboard/dashboard.dart
  frontend/lib/src/features/home_screen.dart
  frontend/lib/src/features/transaction_history/components/transaction_card.dart
  frontend/lib/src/features/transaction_history/data/data.dart
  frontend/lib/src/features/transaction_history/transaction_history.dart
  frontend/lib/src/models/transaction.dart
  frontend/lib/src/navigators/dashboard_screen_navigator.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer : Redempto, dependent, Code Reviewer: Rob

#20 [SIM_FLUTTER-41] [BE] Create user update profile info API
  backend/app/Http/Controllers/AuthController.php
  backend/app/Http/Controllers/UserController.php
  backend/app/Http/Requests/ProfileRequest.php
  backend/app/Http/Requests/UpdatePasswordRequest.php
  backend/routes/api.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#18 [SIM_FLUTTER-60] [BE] Create Get Accounts API
  backend/app/Http/Controllers/AccountController.php
  backend/app/Http/Controllers/UserController.php
  backend/app/Http/Resources/AccountResource.php
  backend/app/Models/Account.php
  backend/app/Models/Transaction.php
  backend/app/Traits/Uuid.php
  backend/config/enums.php
  backend/database/factories/AccountFactory.php
  backend/database/factories/TransactionFactory.php
  backend/database/factories/UserFactory.php
  backend/database/seeders/AccountSeeder.php
  backend/database/seeders/DatabaseSeeder.php
  backend/database/seeders/TransactionSeeder.php
  backend/routes/api.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#13 [SIM_FLUTTER-14] [BE] Create User Sign-up API
  backend/app/Http/Controllers/AuthController.php
  backend/app/Http/Controllers/UserController.php
  backend/app/Http/Requests/LoginRequest.php
  backend/app/Http/Requests/SignupRequest.php
  backend/app/Http/Resources/SignupResource.php
  backend/app/Models/User.php
  backend/routes/api.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer : Redempto

#21 [SIM_FLUTTER-28] [BE] Create get user profile API
  backend/app/Http/Controllers/UserController.php
  backend/routes/api.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#14 [SIM_FLUTTER-62][FE] Create account details page
  frontend/lib/src/components/balance_card.dart
  frontend/lib/src/components/button.dart
  frontend/lib/src/components/graph.dart
  frontend/lib/src/components/indicator.dart
  frontend/lib/src/features/account_details/account_details_page.dart
  frontend/lib/src/features/dashboard/components/account_card.dart
  frontend/lib/src/features/dashboard/dashboard.dart
  frontend/lib/src/features/login/login_page.dart
  frontend/lib/src/features/transaction_history/transaction_history.dart
  frontend/lib/src/models/account.dart
  frontend/lib/src/navigators/dashboard_screen_navigator.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#11 [SIM_FLUTTER-11] [FE] Create User Sign-up Page
  .vscode/launch.json
  frontend/lib/src/components/input/input_field.dart
  frontend/lib/src/components/label.dart
  frontend/lib/src/features/login/login_page.dart
  frontend/lib/src/features/sign_up/components/breadcrumb.dart
  frontend/lib/src/features/sign_up/sign_up_flow.dart
  frontend/lib/src/features/sign_up/sign_up_step_one.dart
  frontend/lib/src/features/sign_up/sign_up_step_two.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Rob

#19 [SIM_FLUTTER-90] [BE] Create logout API
  backend/app/Http/Controllers/AuthController.php
  backend/app/Http/Controllers/UserController.php
  backend/app/Http/Resources/LogoutResource.php
  backend/routes/api.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Rob

#22 [SIM_FLUTTER-7] [BE] Create Admin Delete User API
  backend/app/Http/Controllers/UserController.php
  backend/app/Models/User.php
  backend/routes/api.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Rob

#24 [SIM_FLUTTER-12] [INTEGRATE] Implement User can login
  README.md
  backend/app/Http/Kernel.php
  backend/app/Http/Middleware/LogRequest.php
  backend/config/cors.php
  backend/config/sanctum.php
  backend/routes/api.php
  frontend/.env.example
  frontend/.gitignore
  frontend/android/app/build.gradle
  frontend/lib/main.dart
  frontend/lib/src/components/input/input_field.dart
  frontend/lib/src/controllers/login_controller.dart
  frontend/lib/src/features/login/login_page.dart
  frontend/lib/src/helper/dio.dart
  frontend/lib/src/helper/storage.dart
  frontend/linux/flutter/generated_plugin_registrant.cc
  frontend/linux/flutter/generated_plugins.cmake
  frontend/macos/Flutter/GeneratedPluginRegistrant.swift
  frontend/pubspec.lock
  frontend/pubspec.yaml
  frontend/windows/flutter/generated_plugin_registrant.cc
  frontend/windows/flutter/generated_plugins.cmake
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer : Redempto

#23 [SIM_FLUTTER-52] [BE] Create Get Transactions API
  backend/app/Http/Controllers/TransactionController.php
  backend/app/Http/Resources/TransactionResource.php
  backend/database/factories/TransactionFactory.php
  backend/database/seeders/TransactionSeeder.php
  backend/routes/api.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#26 [SIM_FLUTTER-88] [Integrate] User can logout
  frontend/lib/src/components/auth/auth_header.dart
  frontend/lib/src/features/login/login_page.dart
  frontend/lib/src/helper/dio.dart
  frontend/lib/src/helper/snackbar/show_snackbar.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#28 [SIM_FLUTTER-93] [INTEGRATE] Implement user can change password
  backend/app/Http/Controllers/AuthController.php
  backend/app/Http/Controllers/UserController.php
  backend/app/Http/Middleware/LogRequest.php
  backend/config/sanctum.php
  backend/routes/api.php
  frontend/lib/src/components/auth/auth_header.dart
  frontend/lib/src/components/button.dart
  frontend/lib/src/controllers/change_password_controller.dart
  frontend/lib/src/features/login/login_page.dart
  frontend/lib/src/features/user_profile/profile_change_password.dart
  frontend/lib/src/helper/dio.dart
  frontend/lib/src/helper/storage.dart
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer : Redempto

#29 [SIM_FLUTTER-48] [BE] Create Transfer money API
  backend/app/Http/Controllers/TransactionController.php
  backend/app/Http/Requests/TransactionPostRequest.php
  backend/app/Models/Account.php
  backend/app/Models/Transaction.php
  backend/app/Observers/TransactionObserver.php
  backend/app/Providers/AppServiceProvider.php
  backend/composer.json
  backend/database/seeders/TransactionSeeder.php
  backend/routes/api.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#32 [SIM_FLUTTER-55] [BE] Create filter by category/type of transaction API
  backend/app/Http/Controllers/TransactionController.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#31 SIM_FLUTTER-6 [BE] Create reset password API
  backend/.env.example
  backend/app/Http/Controllers/AuthController.php
  backend/app/Http/Requests/Auth/ForgotPasswordRequest.php
  backend/app/Http/Requests/Auth/ResetPasswordRequest.php
  backend/app/Http/Resources/ForgotPasswordResource.php
  backend/app/Http/Resources/ResetPasswordResource.php
  backend/app/Models/User.php
  backend/app/Notifications/ResetPasswordNotification.php
  backend/routes/api.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen

#25 [SIM_FLUTTER-38] [BE] Create search user API
  backend/app/Http/Controllers/UserController.php
  backend/app/Http/Requests/SearchUserRequest.php
  backend/app/Models/User.php
  backend/routes/api.php
Labels: QA Reviewer : Derick, Code Reviewer : Karlo, Approved by QA, Approved by Dev

#33 [SIM_FLUTTER-58] [BE] Create filter transaction by date API
  backend/app/Http/Controllers/TransactionController.php
  backend/app/Http/Requests/FilterTransactionRequest.php
Labels: QA Reviewer : Derick, Approved by QA, Approved by Dev, Code Reviewer: Stephen
